__background_set(BG_PROP_X, 0, (__background_get(BG_PROP_X, 0) + 0.1))
__background_set(BG_PROP_X, 1, (__background_get(BG_PROP_X, 1) + 0.3))
__background_set(BG_PROP_X, 2, (__background_get(BG_PROP_X, 2) + 0.5))
__background_set(BG_PROP_X, 3, (__background_get(BG_PROP_X, 3) + 0.6))
__background_set(BG_PROP_X, 4, (__background_get(BG_PROP_X, 4) + 1))
__background_set(BG_PROP_X, 5, (__background_get(BG_PROP_X, 5) + 1.5))
__background_set(BG_PROP_X, 6, (__background_get(BG_PROP_X, 6) + 2))
