if (view_xview(0) >= 0)
    __background_set(3, 0, floor((view_xview(0) - (view_xview(0) * scrollspeed))))
gg = (room_width - view_wview(0))
if (view_xview(0) >= gg)
    __background_set(3, 0, floor((gg - (gg * scrollspeed))))
