if (__view_get(VIEW_PROP_CAM_X, 0) >= 0)
    x = (200 + floor((__view_get(VIEW_PROP_CAM_X, 0) - (__view_get(VIEW_PROP_CAM_X, 0) * scrollspeed))))
gg = (room_width - __view_get(VIEW_PROP_CAM_WIDTH, 0))
if (__view_get(VIEW_PROP_CAM_X, 0) >= gg)
    x = (200 + floor((gg - (gg * scrollspeed))))
