if (camera_get_view_x(view_camera[0]) >= 0)
    x = (200 + floor((camera_get_view_x(view_camera[0]) - (camera_get_view_x(view_camera[0]) * scrollspeed))))
gg = (room_width - camera_get_view_width(view_camera[0]))
if (camera_get_view_x(view_camera[0]) >= gg)
    x = (200 + floor((gg - (gg * scrollspeed))))
